import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { NativePanoramaPreview } from './NativePanoramaPreview'
import { readNativePanorama } from './nativePanorama'

vi.mock('./nativePanorama', () => ({ readNativePanorama: vi.fn() }))
afterEach(() => { vi.unstubAllGlobals(); vi.resetAllMocks() })
const bundle = { size: 16, faces: ['front', 'right', 'back', 'left', 'top', 'bottom'].map(name => ({ name, blob: new Blob([new Uint8Array(1024)]) })) }
function setup() {
  const revoke = vi.fn(), create = vi.fn().mockReturnValue('blob:face')
  vi.stubGlobal('URL', { createObjectURL: create, revokeObjectURL: revoke })
  const rendered = render(<NativePanoramaPreview />)
  const select = () => fireEvent.change(screen.getByLabelText('Choose native bundle files'), { target: { files: [new File(['x'], 'manifest.json')] } })
  return { ...rendered, select, revoke, create }
}
it('previews verified faces and releases local URLs when cleared', async () => {
  vi.mocked(readNativePanorama).mockResolvedValue(bundle)
  const { select, revoke } = setup()
  select()
  expect(await screen.findByRole('img', { name: 'Front cube face' })).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Top' }))
  expect(screen.getByRole('img', { name: 'Top cube face' })).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Clear preview' }))
  expect(screen.queryByRole('img')).not.toBeInTheDocument()
  expect(revoke).toHaveBeenCalledTimes(6)
})
it('keeps verified file details visible in both modes and removes them on clear', async () => {
  vi.mocked(readNativePanorama).mockResolvedValue(bundle)
  const { select } = setup()
  expect(screen.getByRole('button', { name: 'Choose bundle files' })).toBeInTheDocument()
  select()
  expect(await screen.findByText(/Bundle verified/)).toHaveTextContent('Bundle verified · 6 faces · 16 × 16 px per face · 6 KiB of image data')
  expect(screen.getByRole('button', { name: 'Replace bundle files' })).toBeInTheDocument()
  for (const face of bundle.faces) expect(screen.getByText(`${face.name}.jpg`)).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Explore 360°' }))
  expect(screen.getByText(/Bundle verified/)).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Clear preview' }))
  expect(screen.queryByText(/Bundle verified/)).not.toBeInTheDocument()
  expect(screen.queryByText('front.jpg')).not.toBeInTheDocument()
})
it('does not retain a verified report when a replacement fails', async () => {
  vi.mocked(readNativePanorama).mockResolvedValueOnce(bundle).mockRejectedValueOnce(new Error('Checksum mismatch'))
  const { select } = setup()
  select()
  await screen.findByText(/Bundle verified/)
  select()
  expect(screen.queryByText(/Bundle verified/)).not.toBeInTheDocument()
  expect(await screen.findByRole('alert')).toHaveTextContent('Checksum mismatch')
  expect(screen.queryByText('front.jpg')).not.toBeInTheDocument()
})
it('opens the native picker from its button and preserves the preview on cancellation', async () => {
  vi.mocked(readNativePanorama).mockResolvedValue(bundle)
  const { select, revoke } = setup()
  const input = screen.getByLabelText('Choose native bundle files')
  const click = vi.spyOn(input, 'click').mockImplementation(() => {})
  fireEvent.click(screen.getByRole('button', { name: 'Choose bundle files' }))
  expect(click).toHaveBeenCalledOnce()
  select()
  await screen.findByText(/Bundle verified/)
  fireEvent.change(input, { target: { files: [] } })
  expect(screen.getByText(/Bundle verified/)).toBeInTheDocument()
  expect(screen.getByRole('img', { name: 'Front cube face' })).toBeInTheDocument()
  expect(revoke).not.toHaveBeenCalled()
  expect(readNativePanorama).toHaveBeenCalledOnce()
})
it('accepts native bundle files dropped onto the inspector', async () => {
  vi.mocked(readNativePanorama).mockResolvedValue(bundle)
  const { create } = setup()
  const files = [new File(['{}'], 'manifest.json'), ...bundle.faces.map(face => new File(['jpeg'], `${face.name}.jpg`))]
  const dropzone = screen.getByRole('group', { name: 'Native panorama bundle dropzone' })
  fireEvent.dragOver(dropzone, { dataTransfer: { files } })
  fireEvent.drop(dropzone, { dataTransfer: { files } })
  expect(await screen.findByRole('img', { name: 'Front cube face' })).toBeInTheDocument()
  expect(readNativePanorama).toHaveBeenCalledWith(files, expect.any(AbortSignal))
  expect(create).toHaveBeenCalledTimes(6)
})
it('shows errors without publishing a partial preview and permits retry', async () => {
  vi.mocked(readNativePanorama).mockRejectedValueOnce(new Error('Checksum mismatch')).mockResolvedValueOnce(bundle)
  const { select, create } = setup()
  select()
  expect(await screen.findByRole('alert')).toHaveTextContent('Checksum mismatch')
  expect(create).not.toHaveBeenCalled()
  select()
  expect(await screen.findByRole('img')).toBeInTheDocument()
})
it('opens the interactive viewer only on request and can return to face inspection', async () => {
  vi.mocked(readNativePanorama).mockResolvedValue(bundle)
  const { select } = setup()
  select()
  await screen.findByRole('img', { name: 'Front cube face' })
  expect(screen.queryByRole('region', { name: 'Interactive native panorama' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Explore 360°' }))
  expect(screen.getByRole('region', { name: 'Interactive native panorama' })).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Inspect faces' }))
  expect(screen.getByRole('img', { name: 'Front cube face' })).toBeInTheDocument()
})
it.each(['clear', 'unmount'])('does not publish a stale selection after %s', async action => {
  let finish!: (value: typeof bundle) => void
  vi.mocked(readNativePanorama).mockReturnValue(new Promise(resolve => { finish = resolve }))
  const { select, create, unmount } = setup()
  select()
  const signal = vi.mocked(readNativePanorama).mock.calls[0][1]
  if (action === 'clear') fireEvent.click(screen.getByRole('button', { name: 'Clear preview' }))
  else unmount()
  expect(signal.aborted).toBe(true)
  await act(async () => { finish(bundle) })
  expect(create).not.toHaveBeenCalled()
})
it.each(['success', 'failure'])('ignores a late %s from a replaced bundle without releasing the current preview', async outcome => {
  let finish!: (value: typeof bundle) => void
  let fail!: (reason: Error) => void
  vi.mocked(readNativePanorama)
    .mockReturnValueOnce(new Promise((resolve, reject) => { finish = resolve; fail = reject }))
    .mockResolvedValueOnce({ ...bundle, size: 32 })
  const { select, create, revoke, unmount } = setup()
  create.mockImplementation(() => `blob:face-${create.mock.calls.length}`)
  select()
  const oldSignal = vi.mocked(readNativePanorama).mock.calls[0][1]
  select()
  expect(oldSignal.aborted).toBe(true)
  await screen.findByText(/32 × 32 px per face/)
  const currentImage = screen.getByRole('img', { name: 'Front cube face' }).getAttribute('src')
  await act(async () => {
    if (outcome === 'success') finish(bundle)
    else fail(new Error('Old bundle failed'))
  })
  expect(screen.getByText(/32 × 32 px per face/)).toBeInTheDocument()
  expect(screen.getByRole('img', { name: 'Front cube face' })).toHaveAttribute('src', currentImage)
  expect(screen.queryByRole('alert')).not.toBeInTheDocument()
  expect(create).toHaveBeenCalledTimes(6)
  expect(revoke).not.toHaveBeenCalled()
  unmount()
  expect(revoke.mock.calls.map(([url]) => url)).toEqual(create.mock.results.map(result => result.value))
})
